#!/bin/sh /etc/rc.common
# Copyright (C) 2019 Onion Corporation

START=90
STOP=90
USE_PROCD=1
DEPENDS="network"

start_service() {
    procd_open_instance
    procd_set_param command python /root/work/ups/db/appMqtt.py
    procd_set_param respawn 31536000 30 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param netdev eth0  # Waits for eth0 to be up
    procd_set_param env HOME=/root  # Optional: Sets environment variables
    procd_close_instance
}
